"""Loads data/catalog.json and provides name/kind/icon lookups for save ids.

The catalog is generated by tools/fetch_catalog.py from howmanydudes.com. IDs
that appear in a save file but not in the catalog (e.g. after a game update
adds new content before the catalog is regenerated) fall back to showing the
raw id; catalog entries that don't appear in the current save are simply
undiscovered or unowned, not an error.
"""

from __future__ import annotations

import functools
import json
from pathlib import Path
from typing import Optional

_REPO_ROOT = Path(__file__).resolve().parent.parent
_DEFAULT_CATALOG_PATH = _REPO_ROOT / "data" / "catalog.json"
_SPRITES_DIR = _REPO_ROOT / "cache" / "sprites"


class Catalog:
    def __init__(self, entries: dict):
        self._entries = entries
        self._icon_cache: dict = {}

    @classmethod
    def load(cls, path: Optional[Path] = None) -> "Catalog":
        path = path or _DEFAULT_CATALOG_PATH
        if not path.is_file():
            return cls({})
        with path.open(encoding="utf-8") as f:
            return cls(json.load(f))

    def __contains__(self, item_id: str) -> bool:
        return item_id in self._entries

    def __len__(self) -> int:
        return len(self._entries)

    def entry(self, item_id: str) -> Optional[dict]:
        return self._entries.get(item_id)

    def name_for(self, item_id: str) -> str:
        entry = self._entries.get(item_id)
        return entry["name"] if entry else item_id

    def kind_for(self, item_id: str) -> Optional[str]:
        entry = self._entries.get(item_id)
        return entry["kind"] if entry else None

    def description_for(self, item_id: str) -> str:
        entry = self._entries.get(item_id)
        return entry.get("description", "") if entry else ""

    def ability_name_for(self, item_id: str) -> Optional[str]:
        entry = self._entries.get(item_id)
        return entry.get("ability_name") if entry else None

    def ids_of_kind(self, kind: str) -> list:
        return [eid for eid, e in self._entries.items() if e["kind"] == kind]

    def sprite_path_for(self, item_id: str) -> Optional[Path]:
        entry = self._entries.get(item_id)
        if entry is None or not entry.get("sprite"):
            return None
        local = _SPRITES_DIR / Path(entry["sprite"]).name
        return local if local.is_file() else None

    def icon_for(self, item_id: str):
        """Return a QPixmap for `item_id`, or None if no sprite is cached
        locally. Memoized. Imports PySide6 lazily so this module - and the
        rest of the model layer that depends on it - stays importable
        without Qt installed."""
        if item_id in self._icon_cache:
            return self._icon_cache[item_id]
        path = self.sprite_path_for(item_id)
        pixmap = None
        if path is not None:
            from PySide6.QtGui import QPixmap

            pixmap = QPixmap(str(path))
            if pixmap.isNull():
                pixmap = None
        self._icon_cache[item_id] = pixmap
        return pixmap


@functools.lru_cache(maxsize=1)
def get_catalog() -> Catalog:
    return Catalog.load()
